export const APPETIZER = [
  {
    id: 1,
    category: 'Appetizer',
    name: 'Garlic Bread',
    description: 'Foot long Italian bread brushed with garlic herb butter & lightly toasted. Served with marinara.',
    images: '/images/menu-items/app/garlic-bread.webp',
    size1: 'Two piece',
    price1: 4.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 2,
    category: 'Appetizer',
    name: 'Sicilian Garlic Bread',
    description: 'Foot long Italian bread brushed with garlic herb butter, topped with mozzarella, & lightly toasted. Served with marinara.',
    images: '/images/menu-items/app/sicilian-garlic-bread.webp',
    size1: 'Two piece',
    price1: 5.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 3,
    category: 'Appetizer',
    name: 'Meatballs & Ricotta',
    description: 'Twin jumbo meatballs accompanied by marinara sauce, ricotta & parmesan.',
    images: '/images/menu-items/app/meatballs-ricotta.webp',
    size1: 'Two piece',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 4,
    category: 'Appetizer',
    name: 'Meatball Sliders',
    description: 'Five crostinis topped with our meatballs, marinara sauce, oregenao, & mozzarella.',
    images: '/images/menu-items/app/meatball-sliders.webp',
    size1: 'Five piece',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 5,
    category: 'Appetizer',
    name: 'Fries',
    description: 'Tossed with salt, black pepper, garlic seasoning, oregano, & parsley.',
    images: '/images/menu-items/app/fries.webp',
    size1: 'Personal size',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 6,
    category: 'Appetizer',
    name: 'Pepperoni Pizza Fries',
    description: 'Bounos-style; seasoned french fries baked with pepperoni, mozzarella, oregano, & finished with marinara sauce.',
    images: '/images/menu-items/app/pepperoni-pizza-fries.webp',
    size1: 'Personal size',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 7,
    category: 'Appetizer',
    name: 'NJ Style Disco Fries',
    description: 'New Jersey diner-style; seasoned french fries baked with mozzarella, topped with a classic brown chicken gravy, & parsley.',
    images: '/images/menu-items/app/disco-fries.webp',
    size1: 'Personal size',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 8,
    category: 'Appetizer',
    name: 'Fried Mushrooms',
    description: 'Cremini mushrooms, coated in a light & crispy seasoned batter, then deep fried to golden brown perfection. Served with ranch dressing.',
    images: '/images/menu-items/app/fried-mushrooms.webp',
    size1: 'Personal size',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 9,
    category: 'Appetizer',
    name: 'Fried Zucchini',
    description: 'Fresh zucchini sticks, Italian bread crumb dredged, then deep fried to golden brown perfection. Served with ranch dressing.',
    images: '/images/menu-items/app/zucchini-sticks.webp',
    size1: 'Personal size',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 10,
    category: 'Appetizer',
    name: 'Fried Mozzarella Sticks',
    description: 'Six mozzarella sticks, Italian bread crumb dredged, then deep fried to golden brown perfection. Served with marinara sauce.',
    images: '/images/menu-items/app/mozzarella-sticks.webp',
    size1: 'Six piece',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 11,
    category: 'Appetizer',
    name: 'Fried Ravioli',
    description: 'Six ricotta stuffed ravioli, lightly Italian bread crumb dredged, then deep fried to golden brown perfection. Served with marinara sauce.',
    images: '/images/menu-items/app/fried-ravioli.webp',
    size1: 'Six piece',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 12,
    category: 'Appetizer',
    name: 'Traditional Chicken Wings',
    description: 'Bone-in fried chicken wings tossed in your choice of sauce. Served with celery sticks, & choice of dressing.',
    images: '/images/menu-items/app/wings.webp',
    size1: 'Six piece',
    price1: 8.75,
    size2: 'Ten piece',
    price2: 14.99,
    size3: null,
    price3: null,
    isWings: true
  },
  {
    id: 13,
    category: 'Appetizer',
    name: 'Boneless Chicken Wings',
    description: 'Boneless fried chicken pieces tossed in your choice of sauce. Served with celery sticks, & choice of dressing.',
    images: '/images/menu-items/app/wings-boneless.webp',
    size1: 'Six piece',
    price1: 8.25,
    size2: 'Ten piece',
    price2: 11.25,
    size3: null,
    price3: null,
    isWings: true
  },
];