export const APPETIZER = [
  {
    id: 10,
    category: 'Appetizer',
    name: 'Garlic Knots',
    description: 'New York style classic. Brushed and baked with garlic, butter, olive oil, and parmesan cheese. Served with marinara.',
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: 'Six piece',
    price1: 4.50,
    size2: 'Twelve piece',
    price2: 7.50,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 11,
    category: 'Appetizer',
    name: 'Garlic Knots with Mozzarella',
    description: 'New York style classic. Brushed and baked with garlic, butter, olive oil, and parmesan cheese. Twice baked with melty mozzarella cheeses. Served with marinara.',
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: 'Six piece',
    price1: 5.50,
    size2: 'Twelve piece',
    price2: 8.50,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 12,
    category: 'Appetizer',
    name: 'Garlic Bread',
    description: 'Foot long Italian bread brushed with garlic herb butter & lightly toasted. Served with marinara.',
    images: '/images/menu-items/app/garlic-bread.webp',
    size1: 'Two piece',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 13,
    category: 'Appetizer',
    name: 'Sicilian Garlic Bread',
    description: 'Foot long Italian bread brushed with garlic herb butter, topped with mozzarella, & lightly toasted. Served with marinara.',
    images: '/images/menu-items/app/sicilian-garlic-bread.webp',
    size1: 'Two piece',
    price1: 7.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 20,
    category: 'Appetizer',
    name: 'Fries',
    description: 'Tossed with salt, black pepper, garlic seasoning, oregano, & parsley.',
    images: '/images/menu-items/app/fries.webp',
    size1: 'Personal size',
    price1: 5.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 21,
    category: 'Appetizer',
    name: 'Meatballs & Ricotta',
    description: 'Twin jumbo meatballs accompanied by marinara sauce, ricotta & parmesan.',
    images: '/images/menu-items/app/meatballs-ricotta.webp',
    size1: 'Two piece',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 22,
    category: 'Appetizer',
    name: 'Meatball Sliders',
    description: 'Five crostinis topped with our meatballs, marinara sauce, oregenao, & mozzarella.',
    images: '/images/menu-items/app/meatball-sliders.webp',
    size1: 'Five piece',
    price1: 10.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },
  {
    id: 23,
    category: 'Appetizer',
    name: 'Pepperoni Pizza Fries',
    description: 'Bounos-style; seasoned french fries baked with pepperoni, mozzarella, oregano, & finished with marinara sauce.',
    images: '/images/menu-items/app/pepperoni-pizza-fries.webp',
    size1: 'Personal size',
    price1: 9.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 24,
    category: 'Appetizer',
    name: 'NJ Style Disco Fries',
    description: 'New Jersey diner-style; seasoned french fries baked with mozzarella, topped with a classic brown chicken gravy, & parsley.',
    images: '/images/menu-items/app/disco-fries.webp',
    size1: 'Personal size',
    price1: 9.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 25,
    category: 'Appetizer',
    name: 'Fried Mushrooms',
    description: 'Cremini mushrooms, coated in a light & crispy seasoned batter, then deep fried to golden brown perfection. Served with ranch dressing.',
    images: '/images/menu-items/app/fried-mushrooms.webp',
    size1: 'Personal size',
    price1: 9.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 26,
    category: 'Appetizer',
    name: 'Fried Zucchini',
    description: 'Fresh zucchini sticks, Italian bread crumb dredged, then deep fried to golden brown perfection. Served with ranch dressing.',
    images: '/images/menu-items/app/zucchini-sticks.webp',
    size1: 'Personal size',
    price1: 9.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 27,
    category: 'Appetizer',
    name: 'Fried Mozzarella Sticks',
    description: 'Six mozzarella sticks, Italian bread crumb dredged, then deep fried to golden brown perfection. Served with marinara sauce.',
    images: '/images/menu-items/app/mozzarella-sticks.webp',
    size1: 'Six piece',
    price1: 9.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 28,
    category: 'Appetizer',
    name: 'Fried Ravioli',
    description: 'Six ricotta stuffed ravioli, lightly Italian bread crumb dredged, then deep fried to golden brown perfection. Served with marinara sauce.',
    images: '/images/menu-items/app/fried-ravioli.webp',
    size1: 'Six piece',
    price1: 9.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 29,
    category: 'Appetizer',
    name: 'Arancini',
    description: 'Italian rice balls that are stuffed, coated with breadcrumbs and deep-fried. Served with a pink vodka sauce.',
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: 'Three Jumbo Rice Balls',
    price1: 9.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isWings: false
  },

  {
    id: 30,
    category: 'Appetizer',
    name: 'Traditional Chicken Wings',
    description: 'Bone-in fried chicken wings tossed in your choice of sauce. Served with celery sticks, & choice of dressing.',
    images: '/images/menu-items/app/wings.webp',
    size1: 'Six piece',
    price1: 11.50,
    size2: 'Ten piece',
    price2: 15.99,
    size3: null,
    price3: null,
    isWings: true
  },

  {
    id: 31,
    category: 'Appetizer',
    name: 'Boneless Chicken Wings',
    description: 'Boneless fried chicken pieces tossed in your choice of sauce. Served with celery sticks, & choice of dressing.',
    images: '/images/menu-items/app/wings-boneless.webp',
    size1: 'Six piece',
    price1: 10.25,
    size2: 'Ten piece',
    price2: 13.25,
    size3: null,
    price3: null,
    isWings: true
  },
];