export const BEVERAGE = [
  {
    id: 1,
    category: 'Beverage',
    name: 'Fountain Drink',
    description: '20 oz drink.',
    images: '/images/menu-items/beverage/fountain.webp',
    size1: '20 oz drink',
    price1: 2.75,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isFountain: true
  },
  {
    id: 2,
    category: 'Beverage',
    name: 'Bottled Soda',
    description: '2 liter bottled soda. Available for take out only.',
    images: '/images/menu-items/beverage/bottled-soda.webp',
    size1: '2 liter bottle',
    price1: 3.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isFountain: false
  },
  {
    id: 3,
    category: 'Beverage',
    name: 'Bottled Water',
    description: '16 oz bottled water.',
    images: '/images/menu-items/beverage/bottled-water.webp',
    size1: '16 oz bottle',
    price1: 1.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isFountain: false
  },
  {
    id: 4,
    category: 'Beverage',
    name: 'Bottled Tea',
    description: 'Bottled Tea.',
    images: '/images/menu-items/beverage/ice-tea.webp',
    size1: '16 oz bottle',
    price1: 2.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isFountain: false
  },
  // {
  //   id: 5,
  //   category: 'Beverage',
  //   name: 'Arizona Lemonade Stand',
  //   description: 'Made with real lemons, fruits,and other natural flavors.',
  //   images: '/images/menu-items/beverage/az-lemonade.webp',
  //   size1: '32 oz bottle',
  //   price1: 6.99,
  //   size2: null,
  //   price2: null,
  //   size3: null,
  //   price3: null,
  //   isFountain: false
  // },
  {
    id: 6,
    category: 'Beverage',
    name: 'Dr Browns Soda',
    description: 'A New York Classic. Black Cherry, Root Beer, or Cream Soda.',
    images: '/images/menu-items/beverage/dr-brown.webp',
    size1: '12 oz can',
    price1: 2.50,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isFountain: false
  },
  {
    id: 7,
    category: 'Beverage',
    name: 'Yoohoo',
    description: 'A New York Classic. Chocolate drink.',
    images: '/images/menu-items/beverage/yoohoo.webp',
    size1: '12 oz bottle',
    price1: 2.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isFountain: false
  },
  {
    id: 8,
    category: 'Beverage',
    name: 'Domestic Beer',
    description: 'Must be consumed in the restaurant.',
    images: '/images/menu-items/beverage/domestic-beer.webp',
    size1: '12 oz bottle',
    price1: 4.25,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isFountain: false
  },
  {
    id: 9,
    category: 'Beverage',
    name: 'Imported Beer',
    description: 'Must be consumed in the restaurant.',
    images: '/images/menu-items/beverage/imported-beer.webp',
    size1: '12 oz bottle',
    price1: 4.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isFountain: false
  },
  {
    id: 10,
    category: 'Beverage',
    name: 'House Red Wine',
    description: 'Must be consumed in the restaurant.',
    images: '/images/menu-items/beverage/red-wine.webp',
    size1: 'By the glass',
    price1: 9.00,
    size2: 'By the bottle',
    price2: 26.00,
    size3: null,
    price3: null,
    isFountain: false
  },
  {
    id: 11,
    category: 'Beverage',
    name: 'House White Wine',
    description: 'Must be consumed in the restaurant.',
    images: '/images/menu-items/beverage/white-wine.webp',
    size1: 'By the glass',
    price1: 9.00,
    size2: 'By the bottle',
    price2: 26.00,
    size3: null,
    price3: null,
    isFountain: false
  },
];