export const COLD_SUB = [
  {
    id: 1,
    category: 'ColdSub',
    name: 'Italian Deli Mix',
    description: 'Foot long Italian bread with salami, capocollo, soppressata, provolone, lettuce, tomatoes & onions. Choice of house dressing, mayonnaise, &/or mustard.',
    images: '/images/menu-items/cold-sub/italian-mix.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 9.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 2,
    category: 'ColdSub',
    name: 'Ham & Provolone',
    description: 'Foot long Italian bread with deli ham, provolone, lettuce, tomatoes & onions. Choice of house dressing, mayonnaise, &/or mustard.',
    images: '/images/menu-items/cold-sub/ham-provalone.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 3,
    category: 'ColdSub',
    name: 'Salami & Provolone',
    description: 'Foot long Italian bread with salami, provolone, lettuce, tomatoes & onions. Choice of house dressing, mayonnaise, &/or mustard.',
    images: '/images/menu-items/cold-sub/salami-provalone.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 4,
    category: 'ColdSub',
    name: 'Capocollo & Provolone',
    description: 'Foot long Italian bread with capocollo, provolone, lettuce, tomatoes & onions. Choice of house dressing, mayonnaise, &/or mustard.',
    images: '/images/menu-items/cold-sub/cappi-provalone.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 5,
    category: 'ColdSub',
    name: 'Pepperoni & Provolone',
    description: 'Foot long Italian bread with pepperoni, provolone, lettuce, tomatoes & onions. Choice of house dressing, mayonnaise, &/or mustard.',
    images: '/images/menu-items/cold-sub/pepperoni-provalone.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
];