export const DESSERT = [
  {
    id: 1,
    category: 'Dessert',
    name: 'Black & White Cookie',
    description: 'Direct from NYC a large cookie frosted half vanilla & half chocolate.',
    images: '/images/menu-items/dessert/black-white-cookie.webp',
    size1: 'Single jumbo cookie',
    price1: 3.75,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 2,
    category: 'Dessert',
    name: 'Crumb Cake',
    description: 'A delicious NYC crumb cake.',
    images: '/images/menu-items/dessert/crumb-cake.webp',
    size1: 'Single slice',
    price1: 4.50,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 3,
    category: 'Dessert',
    name: 'Cannoli',
    description: 'Cannoli shell filled with a sweet, creamy filling containing ricotta, mini chocolate chips, & topped with crushed pistachios.',
    images: '/images/menu-items/dessert/cannoli.webp',
    size1: 'Single jumbo tube',
    price1: 5.49,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 4,
    category: 'Dessert',
    name: 'Tiramisu',
    description: 'Italian dessert made of ladyfingers dipped in coffee, layered with a whipped mascarpone, & cocoa.',
    images: '/images/menu-items/dessert/tiramisu.webp',
    size1: 'Single slice',
    price1: 6.49,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 5,
    category: 'Dessert',
    name: 'Cheese Cake',
    description: 'NYC-style cheese cake with vanilla cream cheese filling in a graham cracker crust.',
    images: '/images/menu-items/dessert/cheese-cake.webp',
    size1: 'Single slice',
    price1: 6.49,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 6,
    category: 'Dessert',
    name: 'Limoncello Cake',
    description: 'Fluffy sponge cake with limoncello mascarpone and cream cheese frosting.',
    images: '/images/menu-items/dessert/lemoncello.webp',
    size1: 'Single slice',
    price1: 6.49,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 7,
    category: 'Dessert',
    name: 'Pistachio Ricotta Cake',
    description: 'A combination of smooth ricotta filling, crushed pistachio, & a delicsous frosting.',
    images: '/images/menu-items/dessert/pistachio-ricotta.webp',
    size1: 'Single slice',
    price1: 6.49,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 8,
    category: 'Dessert',
    name: 'Zeppolis',
    description: 'Italian deep-fried dough topped with powdered sugar.',
    images: '/images/menu-items/dessert/zeppolis.webp',
    size1: 'A bakers dozen',
    price1: 6.49,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
];