export const ENTREE = [
  {
    id: 1,
    category: 'Entree',
    name: 'Chicken Parmigiana',
    description: 'Breaded chicken cutlets covered with marinara sauce & mozzarella. Served with a side of pasta, small salad, & small Italian bread.',
    images: '/images/menu-items/entree/chicken-parm.webp',
    size1: 'Dinner portion for one',
    price1: 20.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 2,
    category: 'Entree',
    name: 'Eggplant Parmigiana',
    description: 'Breaded eggplant cutlets covered with marinara sauce & mozzarella. Served with a side of pasta, small salad, & small Italian bread.',
    images: '/images/menu-items/entree/eggplant-parm.webp',
    size1: 'Dinner portion for one',
    price1: 20.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 3,
    category: 'Entree',
    name: 'Lasagna',
    description: 'A baked six layer Neapolitan style lasagna stacked with bechamel, ground beef, marinara, ricotta, mozzarella, & parmesan. Served with a side of pasta, small salad, & small Italian bread.',
    images: '/images/menu-items/entree/lasagna.webp',
    size1: 'Dinner portion for one',
    price1: 19.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 4,
    category: 'Entree',
    name: 'Cheese Ravioli',
    description: 'Six jumbo ricotta stuffed ravioli topped with marinara sauce, parmesan, & Italian herbs. Served with a side of pasta, small salad, & small Italian bread.',
    images: '/images/menu-items/entree/ravioli.webp',
    size1: 'Dinner portion for one',
    price1: 17.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 5,
    category: 'Entree',
    name: 'Pasta & Marinara Sauce',
    description: 'Choice of pasta topped with marinara sauce, parmesan, & Italian herbs. Served with a side of pasta, small salad, & small Italian bread.',
    images: '/images/menu-items/entree/pasta-tomato-sauce.webp',
    size1: 'Dinner portion for one',
    price1: 9.49,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 6,
    category: 'Entree',
    name: 'Pasta & Meat Sauce',
    description: 'Choice of pasta topped with meat sauce, parmesan, & Italian herbs. Served with a side of pasta, small salad, & small Italian bread.',
    images: '/images/menu-items/entree/pasta-meat-sauce.webp',
    size1: 'Dinner portion for one',
    price1: 14.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 7,
    category: 'Entree',
    name: 'Pasta & Meatballs',
    description: 'Choice of pasta topped with marinara sauce, two jumbo meatballs, parmesan, & Italian herbs. Served with a side of pasta, small salad, & small Italian bread.',
    images: '/images/menu-items/entree/pasta-meatballs.webp',
    size1: 'Dinner portion for one',
    price1: 14.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 8,
    category: 'Entree',
    name: 'Pasta & Saugage',
    description: 'Choice of pasta topped with marinara sauce, two sausage links, parmesan, & Italian herbs. Served with a side of pasta, small salad, & small Italian bread.',
    images: '/images/menu-items/entree/pasta-sausage.webp',
    size1: 'Dinner portion for one',
    price1: 14.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
];