export const HOT_SUB = [
  {
    id: 1,
    category: 'HotSub',
    name: 'Meatball Parmesan',
    description: 'Foot long Italian bread with meatballs, marinara sauce, mozzarella, oregano, & lightly toasted.',
    images: '/images/menu-items/hot-sub/meatball-parm.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 10.50,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 2,
    category: 'HotSub',
    name: 'Sausage Parmesan',
    description: 'Foot long Italian bread with suasage links, marinara sauce, mozzarella, oregano, & lightly toasted.',
    images: '/images/menu-items/hot-sub/sausage-parm.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 10.50,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 3,
    category: 'HotSub',
    name: 'Chicken Parmesan',
    description: 'Foot long Italian bread with breaded chicken cutlets, marinara sauce, mozzarella, oregano, & lightly toasted.',
    images: '/images/menu-items/hot-sub/chicken-parm.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 11.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 4,
    category: 'HotSub',
    name: 'Eggplant Parmesan',
    description: 'Foot long Italian bread with breaded eggplant cutlets, marinara sauce, mozzarella, oregano, & lightly toasted.',
    images: '/images/menu-items/hot-sub/eggplant-parm.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 11.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 5,
    category: 'HotSub',
    name: 'Pepperoni Melt',
    description: 'Foot long Italian bread with pepperoni, marinara, mozzarella, oregano, & lightly toasted.',
    images: '/images/menu-items/hot-sub/pepperoni-melt.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 10.50,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 6,
    category: 'HotSub',
    name: 'Sausage, Onions, Peppers',
    description: 'Foot long Italian bread with sauteed sausage, onions, peppers, oregano, & lightly toasted.',
    images: '/images/menu-items/hot-sub/philly-steak.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 10.50,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 7,
    category: 'HotSub',
    name: 'Philly Steak',
    description: 'Foot long Italian bread with sauteed steak, & onions. Topped with choice of melted cheese or cheese wiz, & lightly toasted.',
    images: '/images/menu-items/hot-sub/sausage-onion-pepper.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 11.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 8,
    category: 'HotSub',
    name: 'Philly Chicken',
    description: 'Foot long Italian bread with sauteed chicken breast, & onions. Topped with choice of melted cheese or cheese wiz, & lightly toasted.',
    images: '/images/menu-items/hot-sub/philly-chicken.webp',
    size1: 'Twelve inches, serves one-two',
    price1: 11.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
];