export const NY_SPECIALTY = [
  {
    id: 1,
    category: 'NYSpecialty',
    name: 'Drakes Devil Dogs',
    description: 'Creme filled devils food cakes.',
    images: '/images/menu-items/ny-favorite/devil-dog.webp',
    size1: '8 count individually wrapped',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 2,
    category: 'NYSpecialty',
    name: 'Drakes Coffe Cakes',
    description: 'Cakes with cinnamon streusel topping.',
    images: '/images/menu-items/ny-favorite/coffee-cake.webp',
    size1: '8 count individually wrapped',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 3,
    category: 'NYSpecialty',
    name: 'Drakes Ring Dings',
    description: 'Frosted creme filled devils food cakes.',
    images: '/images/menu-items/ny-favorite/ring-ding.webp',
    size1: '8 count individually wrapped',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 4,
    category: 'NYSpecialty',
    name: 'Drakes Funny Bones',
    description: 'Frosted peanut butter creme filled devils food cakes.',
    images: '/images/menu-items/ny-favorite/funny-bone.webp',
    size1: '10 count twin wrapped',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 5,
    category: 'NYSpecialty',
    name: 'Drakes Yodels',
    description: 'Frosted creme filled devils food cakes.',
    images: '/images/menu-items/ny-favorite/yodel.webp',
    size1: '10 count twin wrapped',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 6,
    category: 'NYSpecialty',
    name: 'Drakes Yankee Doodles',
    description: 'Creme filled devils food cakes.',
    images: '/images/menu-items/ny-favorite/yankee-doodle.webp',
    size1: '8 count individually wrapped',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 7,
    category: 'NYSpecialty',
    name: 'Drakes Yodels Boston Creme',
    description: 'Frosted creme filled golden cakes.',
    images: '/images/menu-items/ny-favorite/yodel-boston-creme.webp',
    size1: '10 count twin wrapped',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 8,
    category: 'NYSpecialty',
    name: 'Polly-O Ricotta Cheese',
    description: 'Premium Italian natural ricotta cheese. A New York favorite.',
    images: '/images/menu-items/ny-favorite/polly-o-ricotta.webp',
    size1: '5 lb',
    price1: 17.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 9,
    category: 'NYSpecialty',
    name: 'Mikes Hot Honey',
    description: 'Infused with chilies.',
    images: '/images/menu-items/ny-favorite/mikes-hot-honey.webp',
    size1: '12 oz',
    price1: 10.00,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 10,
    category: 'NYSpecialty',
    name: 'Foxs u-bet Syrup',
    description: 'This extra-thick U-Bet Chocolate or Vanilla Syrup is the perfect companion for egg creams, ice cream sundaes, milkshakes, chocolate milk, and pancakes! This fat-free chocolate syrup has a rich chocolate flavor and smooth, velvety texture.',
    images: '/images/menu-items/ny-favorite/fox-u-bet.webp',
    size1: '22 oz',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  }
];