export const SALAD = [
  {
    id: 1,
    category: 'Salad',
    name: 'Caesar Salad',
    description: 'Romaine lettuce, Italian style croutons, caesar dressing, & parmesan.',
    images: '/images/menu-items/salad/caesar.webp',
    size1: 'Small, serves one-two',
    price1: 5.25,
    size2: 'Large, serves two-three',
    price2: 7.99,
    size3: null,
    price3: null,
    isSaladDressing: true
  },
  {
    id: 2,
    category: 'Salad',
    name: 'House Salad',
    description: 'Romaine lettuce, tomatoes, onions, black olives, oregano, parmesan, & choice of dressing.',
    images: '/images/menu-items/salad/toss.webp',
    size1: 'Small, serves one-two',
    price1: 5.25,
    size2: 'Large, serves two-three',
    price2: 7.99,
    size3: null,
    price3: null,
    isSaladDressing: true
  },
  {
    id: 3,
    category: 'Salad',
    name: 'Chef Salad',
    description: 'Romaine lettuce, tomatoes, onions, black olives, banana peppers, provolone, deli ham, oregano, parmesan, & choice of dressing.',
    images: '/images/menu-items/salad/chef.webp',
    size1: null,
    price1: null,
    size2: 'Large, serves two-three',
    price2: 11.99,
    size3: null,
    price3: null,
    isSaladDressing: true
  },
  {
    id: 4,
    category: 'Salad',
    name: 'Chicken Cutlet Salad',
    description: 'Romaine lettuce, tomatoes, onions, black olives, bananas peppers, sliced chicken cutlets, oregano, parmesan, & choice of dressing.',
    images: '/images/menu-items/salad/chicken-cutlet.webp',
    size1: null,
    price1: null,
    size2: 'Large, serves two-three',
    price2: 11.99,
    size3: null,
    price3: null,
    isSaladDressing: true
  },
  {
    id: 5,
    category: 'Salad',
    name: 'Antipasto',
    description: 'Romaine lettuce, tomatoes, onions, black olives, mild giardiniera, provolone, salami, cappocolo, oregano, parmesan, & choice of dressing.',
    images: '/images/menu-items/salad/antipasto.webp',
    size1: null,
    price1: null,
    size2: 'Large, serves two-three',
    price2: 11.99,
    size3: null,
    price3: null,
    isSaladDressing: true
  },
  {
    id: 6,
    category: 'Salad',
    name: 'Caprese',
    description: 'Mozzarella fresca, vine-ripened tomatoes, olive oil, balsamic fig glaze, basil puree, salt, & pepper.',
    images: '/images/menu-items/salad/caprese.webp',
    size1: null,
    price1: null,
    size2: 'Large, serves two-three',
    price2: 8.49,
    size3: null,
    price3: null,
    isSaladDressing: false
  },
];