export const SIDE_ORDER = [
  {
    id: 1,
    category: 'SideOrder',
    name: 'Side of Pasta',
    description: 'Choice of pasta topped with marinara sauce, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/pasta.webp',
    size1: 'Side portion',
    price1: 4.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 2,
    category: 'SideOrder',
    name: 'Side of Pasta & Meatball',
    description: 'Choice of pasta topped with marinara sauce, one jumbo meatball, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/meatball-pasta.webp',
    size1: 'Side portion',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 3,
    category: 'SideOrder',
    name: 'Side of Pasta & Sausage',
    description: 'Choice of pasta topped with marinara sauce, one sausage link, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/sausage-pasta.webp',
    size1: 'Side portion',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 4,
    category: 'SideOrder',
    name: 'Side of Meatballs',
    description: 'Twin jumbo meatballs topped with marinara sauce, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/meatballs.webp',
    size1: 'Two jumbo meatballs',
    price1: 4.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 5,
    category: 'SideOrder',
    name: 'Side of Sausage',
    description: 'Twin sweet Italian sausage links topped with marinara sauce, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/sausage.webp',
    size1: 'Two links',
    price1: 4.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 6,
    category: 'SideOrder',
    name: 'Garlic Bread',
    description: 'Foot long Italian bread brushed with garlic herb butter & lightly toasted. Served with marinara.',
    images: '/images/menu-items/app/garlic-bread.webp',
    size1: '12 inch baguette',
    price1: 4.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 7,
    category: 'SideOrder',
    name: 'Fries',
    description: 'Tossed with salt, black pepper, garlic seasoning, oregano, & parsley.',
    images: '/images/menu-items/app/fries.webp',
    size1: 'Side of fries',
    price1: 3.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
];