export const SPECIALTY_PIZZA = [
  {
    id: 1,
    category: 'Specialty Pizza',
    name: 'Grandma Pie',
    description: 'Long Island-style; a rustic rectangular pan pizza crust, topped with fresh mozzarella, garlic, & stone deck oven baked. Finished with a fresh tomato sauce, basil puree, & parmesan cheese.',
    images: '/images/menu-items/pizza/specialty-grandma-pie.webp',
    size1: 'Small, 8 cut',
    price1: 18.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 2,
    category: 'Specialty Pizza',
    name: 'Margherita Buono',
    description: 'Neapolitan-style; a thin, round crust, topped with fresh mozzarella, & stone deck oven baked. Finished with a fresh tomato sauce, & basil puree.',
    images: '/images/menu-items/pizza/specialty-margherita-pizza.webp',
    size1: 'Small 14 inch, 6 cut',
    price1: 17.99,
    size2: null,
    price2: null,
    size3: 'Extra Large 18 inch, 8 cut',
    price3: 21.99
  },
  {
    id: 3,
    category: 'Specialty Pizza',
    name: 'Meat Lover',
    description: 'Neapolitan-style; a thin round crust topped with a fresh tomato sauce, pepperoni, sausage, meatballs, bacon, mozzarella, oregano, & stone deck oven baked.',
    images: '/images/menu-items/pizza/specialty-meat-lover.webp',
    size1: 'Small 14 inch, 6 cut',
    price1: 24.99,
    size2: 'Large 16 inch, 8 cut',
    price2: 26.99,
    size3: 'Extra Large 18 inch, 8 cut',
    price3: 28.99
  },
  {
    id: 4,
    category: 'Specialty Pizza',
    name: 'Vegetarian',
    description: 'Neapolitan-style; a thin round crust topped with a fresh tomato sauce, mushrooms, green bell peppers, onions, mozzarella, oregano, & stone deck oven baked.',
    images: '/images/menu-items/pizza/specialty-veggi.webp',
    size1: 'Small 14 inch, 6 cut',
    price1: 24.99,
    size2: 'Large 16 inch, 8 cut',
    price2: 26.99,
    size3: 'Extra Large 18 inch, 8 cut',
    price3: 28.99
  },
  {
    id: 5,
    category: 'Specialty Pizza',
    name: 'Works',
    description: 'Neapolitan-style; a thin round crust topped with a fresh tomato sauce, pepperoni, sausage, mushrooms, green bell peppers, onions, mozzarella, oregano, & stone deck oven baked.',
    images: '/images/menu-items/pizza/specialty-works.webp',
    size1: 'Small 14 inch, 6 cut',
    price1: 27.99,
    size2: 'Large 16 inch, 8 cut',
    price2: 29.99,
    size3: 'Extra Large 18 inch, 8 cut',
    price3: 31.99
  },
  {
    id: 6,
    category: 'Specialty Pizza',
    name: 'Baked Ziti',
    description: 'Neapolitan-style; a thin round crust topped with a fresh tomato sauce, ricotta, ziti pasta, mozzarella, oregano, & stone deck oven baked.',
    images: '/images/menu-items/pizza/specialty-ziti.webp',
    size1: null,
    price1: null,
    size2: 'Large 16 inch, 8 cut',
    price2: 27.99,
    size3: null,
    price3: null
  },
];