export const STROMBOLI = [
  {
    id: 1,
    category: 'Stromboli',
    name: 'Salami, Capocollo, Soppressata, & Provolone',
    description: 'An Italian turnover made with leavened dough & rolled. Stuffed with salami, capocollo, soppressata, provolone. & stone deck oven baked. Served with marinara.',
    images: '/images/menu-items/stromboli/stromboli.webp',
    size1: 'Large, serves one-two',
    price1: 14.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 2,
    category: 'Stromboli',
    name: 'Sausage, Pepper, & Onion',
    description: 'An Italian turnover made with leavened dough & rolled. Stuffed with sausage, onions, green bell peppers, mozzarella, & stone deck oven baked. Served with marinara.',
    images: '/images/menu-items/stromboli/stromboli.webp',
    size1: 'Large, serves one-two',
    price1: 14.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 3,
    category: 'Stromboli',
    name: 'Meatball & Mozzarella',
    description: 'An Italian turnover made with leavened dough & rolled. Stuffed with meatballs, marinara, mozzarella, & stone deck oven baked. Served with marinara.',
    images: '/images/menu-items/stromboli/stromboli.webp',
    size1: 'Large, serves one-two',
    price1: 13.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 4,
    category: 'Stromboli',
    name: 'Eggplant & Mozzarella',
    description: 'An Italian turnover made with leavened dough & rolled. Stuffed with breaded eggplant cutlets, marinara, mozzarella, & stone deck oven baked. Served with marinara.',
    images: '/images/menu-items/stromboli/stromboli.webp',
    size1: 'Large, serves one-two',
    price1: 14.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 5,
    category: 'Stromboli',
    name: 'Chicken & Mozzarella',
    description: 'An Italian turnover made with leavened dough & rolled. Stuffed with breaded chicken cutlets, marinara, mozzarella, & stone deck oven baked. Served with marinara.',
    images: '/images/menu-items/stromboli/stromboli.webp',
    size1: 'Large, serves one-two',
    price1: 14.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 6,
    category: 'Stromboli',
    name: 'Meatballs, Sausage, Pepperoni, & Mozzarella',
    description: 'An Italian turnover made with leavened dough & rolled. Stuffed with meatballs, sausage, pepperoni, marinara, mozzarella, & stone deck oven baked. Served with marinara.',
    images: '/images/menu-items/stromboli/stromboli.webp',
    size1: 'Large, serves one-two',
    price1: 14.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
];