export const APPETIZER = [
  {
    id: 1,
    category: 'Appetizer',
    name: 'Chicken Wings',
    description: null,
    images: '/images/catering-menu/app/wings.webp',
    size1: 'Half Tray',
    price1: 'Market',
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 2,
    category: 'Appetizer',
    name: 'Boneless Chicken Wing',
    description: 'Choice of Marinara or Ranch Dressing. PORTIONS 1/2 TRAYS FEEDS 10-12 People.',
    images: '/images/catering-menu/app/wings-boneless.webp',
    size1: 'Half Tray',
    price1: 'Market',
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 3,
    category: 'Appetizer',
    name: 'Fried Zucchini',
    description: 'Choice of Marinara or Ranch Dressing. PORTIONS 1/2 TRAYS FEEDS 10-12 People.',
    images: '/images/catering-menu/app/zuchini.webp',
    size1: 'Half Tray',
    price1: 40,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 4,
    category: 'Appetizer',
    name: 'Fried Mushrooms',
    description: 'Choice of Marinara or Ranch Dressing. PORTIONS 1/2 TRAYS FEEDS 10-12 People.',
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: 'Half Tray',
    price1: 40,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 5,
    category: 'Appetizer',
    name: 'Fried Mozzarella Sticks',
    description: 'Choice of Marinara or Ranch Dressing. PORTIONS 1/2 TRAYS FEEDS 10-12 People.',
    images: '/images/catering-menu/app/mozzarella.webp',
    size1: 'Half Tray',
    price1: 40,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 6,
    category: 'Appetizer',
    name: 'Fried Raviolis',
    description: 'Choice of Marinara or Ranch Dressing. PORTIONS 1/2 TRAYS FEEDS 10-12 People.',
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: 'Half Tray',
    price1: 40,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
];