export const ENTREE = [
  {
    id: 1,
    category: 'Entree',
    name: 'Chicken Parm',
    description: null,
    images: '/images/catering-menu/entree/chicken-parm.webp',
    size1: 'Half Tray',
    price1: 70,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 2,
    category: 'Entree',
    name: 'Eggplant Parm',
    description: null,
    images: '/images/catering-menu/entree/eggplant-parm.webp',
    size1: 'Half Tray',
    price1: 65,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 3,
    category: 'Entree',
    name: 'Sausage Onions Peppers',
    description: null,
    images: '/images/catering-menu/entree/sausage-onion-peppers.webp',
    size1: 'Half Tray',
    price1: 70,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 4,
    category: 'Entree',
    name: 'Baked Ziti',
    description: null,
    images: '/images/catering-menu/entree/baked-penne.webp',
    size1: 'Half Tray',
    price1: 60,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 5,
    category: 'Entree',
    name: 'Ravioli',
    description: null,
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: 'Half Tray',
    price1: 60,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 6,
    category: 'Entree',
    name: 'Manicotti',
    description: null,
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: 'Half Tray',
    price1: 70,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 7,
    category: 'Entree',
    name: 'Stuffed Shells',
    description: null,
    images: '/images/catering-menu/entree/stuffed-shells.webp',
    size1: 'Half Tray',
    price1: 70,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
  {
    id: 8,
    category: 'Entree',
    name: 'Lasagna',
    description: null,
    images: '/images/catering-menu/entree/lasagna.webp',
    size1: 'Half Tray',
    price1: 90,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
];