export const PASTA = [
  {
    id: 1,
    category: 'Pasta',
    name: 'Marinara',
    description: null,
    images: '/images/catering-menu/pasta/marinara.webp',
    size1: 'Half Tray',
    price1: 30,
    size2: 'Full Tray',
    price2: 60,
    size3: null,
    price3: null,
    addBrocoli: 'Add Broccoli',
    addBrocoliPrice: 15,
    addChicken: 'Add Chicken',
    addChickenPrice: 30
  },
  {
    id: 2,
    category: 'Pasta',
    name: 'Garlic & Oil',
    description: null,
    images: '/images/catering-menu/pasta/garlic-oil.webp',
    size1: 'Half Tray',
    price1: 30,
    size2: 'Full Tray',
    price2: 60,
    size3: null,
    price3: null,
    addBrocoli: 'Add Broccoli',
    addBrocoliPrice: 15,
    addChicken: 'Add Chicken',
    addChickenPrice: 30
  },
  {
    id: 3,
    category: 'Pasta',
    name: 'Alfredo',
    description: null,
    images: '/images/catering-menu/pasta/alfredo.webp',
    size1: 'Half Tray',
    price1: 60,
    size2: 'Full Tray',
    price2: 120,
    size3: null,
    price3: null,
    addBrocoli: 'Add Broccoli',
    addBrocoliPrice: 15,
    addChicken: 'Add Chicken',
    addChickenPrice: 30
  },
  {
    id: 4,
    category: 'Pasta',
    name: 'Pink Vodka',
    description: null,
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: 'Half Tray',
    price1: 60,
    size2: 'Full Tray',
    price2: 120,
    size3: null,
    price3: null,
    addBrocoli: 'Add Broccoli',
    addBrocoliPrice: 15,
    addChicken: 'Add Chicken',
    addChickenPrice: 30
  },
];